---  
name: Delete GitHub Actions cache for repository

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub Actions Documentation
# https://docs.github.com/en/github-ae@latest/actions

on:
  # Run on Sundays at 10:15 AM UTC
  schedule:
    - cron: '15 10 * * 0'
  # or on button click
  workflow_dispatch:

env:
  # Use github.repository (<account>/<repo>)
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  call-cleanup:
    uses: rlaiola/ci-templates/.github/workflows/clean-cache.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
